#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
# Source0 file verified with key 0x97D9123DE37A484F (me@victortoso.com)
#
Name     : spice-vdagent
Version  : 0.22.0
Release  : 2
URL      : https://www.spice-space.org/download/releases/spice-vdagent-0.22.0.tar.bz2
Source0  : https://www.spice-space.org/download/releases/spice-vdagent-0.22.0.tar.bz2
Source1  : https://www.spice-space.org/download/releases/spice-vdagent-0.22.0.tar.bz2.sig
Summary  : No detailed summary available
Group    : Development/Tools
License  : GPL-3.0
Requires: spice-vdagent-bin = %{version}-%{release}
Requires: spice-vdagent-config = %{version}-%{release}
Requires: spice-vdagent-data = %{version}-%{release}
Requires: spice-vdagent-license = %{version}-%{release}
Requires: spice-vdagent-man = %{version}-%{release}
Requires: spice-vdagent-services = %{version}-%{release}
BuildRequires : pkgconfig(alsa)
BuildRequires : pkgconfig(dbus-1)
BuildRequires : pkgconfig(gio-unix-2.0)
BuildRequires : pkgconfig(glib-2.0)
BuildRequires : pkgconfig(gtk+-3.0)
BuildRequires : pkgconfig(gtk4)
BuildRequires : pkgconfig(libdrm)
BuildRequires : pkgconfig(libsystemd)
BuildRequires : pkgconfig(pciaccess)
BuildRequires : pkgconfig(spice-protocol)
BuildRequires : pkgconfig(x11)
BuildRequires : pkgconfig(xfixes)
BuildRequires : pkgconfig(xinerama)
BuildRequires : pkgconfig(xrandr)

%description
Spice agent for Linux
=====================
The spice agent for Linux consists of 2 parts, a daemon spice-vdagentd and
a per X-session process spice-vdagent. The daemon gets started in Spice guests
through a Sys-V initscript or a systemd unit. The per X-session gets
automatically started in desktop environments which honor /etc/xdg/autostart,
and under gdm.

%package bin
Summary: bin components for the spice-vdagent package.
Group: Binaries
Requires: spice-vdagent-data = %{version}-%{release}
Requires: spice-vdagent-config = %{version}-%{release}
Requires: spice-vdagent-license = %{version}-%{release}
Requires: spice-vdagent-services = %{version}-%{release}

%description bin
bin components for the spice-vdagent package.


%package config
Summary: config components for the spice-vdagent package.
Group: Default

%description config
config components for the spice-vdagent package.


%package data
Summary: data components for the spice-vdagent package.
Group: Data

%description data
data components for the spice-vdagent package.


%package license
Summary: license components for the spice-vdagent package.
Group: Default

%description license
license components for the spice-vdagent package.


%package man
Summary: man components for the spice-vdagent package.
Group: Default

%description man
man components for the spice-vdagent package.


%package services
Summary: services components for the spice-vdagent package.
Group: Systemd services

%description services
services components for the spice-vdagent package.


%prep
%setup -q -n spice-vdagent-0.22.0
cd %{_builddir}/spice-vdagent-0.22.0

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1661989136
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=auto "
export FCFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export FFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=auto "
%configure --disable-static --with-init-script=systemd
make  %{?_smp_mflags}

%install
export SOURCE_DATE_EPOCH=1661989136
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/spice-vdagent
cp %{_builddir}/spice-vdagent-%{version}/COPYING %{buildroot}/usr/share/package-licenses/spice-vdagent/8624bcdae55baeef00cd11d5dfcfa60f68710a02 || :
%make_install

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/spice-vdagent
/usr/bin/spice-vdagentd

%files config
%defattr(-,root,root,-)
/usr/lib/tmpfiles.d/spice-vdagentd.conf
/usr/lib/udev/rules.d/70-spice-vdagentd.rules

%files data
%defattr(-,root,root,-)
/usr/share/gdm/autostart/LoginWindow/spice-vdagent.desktop
/usr/share/gdm/greeter/autostart/spice-vdagent.desktop

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/spice-vdagent/8624bcdae55baeef00cd11d5dfcfa60f68710a02

%files man
%defattr(0644,root,root,0755)
/usr/share/man/man1/spice-vdagent.1
/usr/share/man/man1/spice-vdagentd.1

%files services
%defattr(-,root,root,-)
/usr/lib/systemd/system/spice-vdagentd.service
/usr/lib/systemd/system/spice-vdagentd.socket
/usr/lib/systemd/user/spice-vdagent.service
